name: Build on Windows

on:
  push:
    branches:
      - WorkflowTesting
  pull_request:
    branches:
      - WorkflowTesting

jobs:
  build:
    runs-on: windows-latest

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v3

      - name: Download Swift
        shell: pwsh
        run: |
          $installerUrl = "https://download.swift.org/swift-6.0.3-release/windows10/swift-6.0.3-RELEASE/swift-6.0.3-RELEASE-windows10.exe"
          Write-Output "Downloading Swift installer from $installerUrl..."
          curl.exe -L -s -o .\swift_installer.exe $installerUrl

      - name: Install Swift
          Start-Process .\swift_installer.exe -ArgumentList /install, /quiet, /norestart -Wait -PassThru -Verb RunAs

      - name: Swift Version
        shell: pwsh
        run: swift -v


      # - name: Set up Swift
      #   uses: compnerd/gha-setup-swift@main
      #   with:
      #     branch: swift-6.0.3-release
      #     tag: 6.0.3-RELEASE
      
      # - name: Install vcpkg
      #   run: |
      #     git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
      #     cd C:\vcpkg
      #     bootstrap-vcpkg.bat

      # - name: Install SDL3 via vcpkg
      #   run: |
      #     C:\vcpkg\vcpkg.exe install SDL3

      # - name: Build Swift Project
      #   run: swift build --package-path .